default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: scrap_development

test:
  <<: *default
  database: scrap_test

production:
  adapter: postgresql
  encoding: unicode
  host: postgres.railway.internal
  username: postgres
  password: sjkGwcoxWFnOjTdbfnEkBFtgczszHVXG
  pool: 5
  url: postgresql://postgres:sjkGwcoxWFnOjTdbfnEkBFtgczszHVXG@postgres.railway.internal:5432/railway
