default: &default
  adapter: postgresql
  encoding: unicode
  host: dpg-d5tj58koud1c73966r60-a
  username: scrap_rugw_user
  password: i7Jkvdjh1bHRxBr32D6h07PpwfpvRR3m
  pool: 5
  url: postgresql://scrap_rugw_user:i7Jkvdjh1bHRxBr32D6h07PpwfpvRR3m@dpg-d5tj58koud1c73966r60-a/scrap_rugw
  database: scrap_rugw

development:
  <<: *default
  database: scrap_development

test:
  <<: *default
  database: scrap_test

production:
  adapter: postgresql
  encoding: unicode
  host: dpg-d5tj58koud1c73966r60-a
  username: scrap_rugw_user
  password: i7Jkvdjh1bHRxBr32D6h07PpwfpvRR3m
  pool: 5
  url: postgresql://scrap_rugw_user:i7Jkvdjh1bHRxBr32D6h07PpwfpvRR3m@dpg-d5tj58koud1c73966r60-a/scrap_rugw
  database: scrap_rugw
